app:
  name: "CIRC Platform (MVP)"
  timezone: "UTC"

paths:
  input_dir: "data/raw"
  rules_dir: "rules"
  output_root: "output"

pipeline:
  correlation_window_minutes: 15
  min_shared_entities: 1
  max_alerts_per_incident: 500
  severity_escalation_threshold: 3

org:
  approved_regions: ["us-east-1", "us-west-2", "eu-west-1"]

enrichment:
  enable_ioc_extraction: true
  enable_link_enrichment: true
  abuseipdb_base: "https://www.abuseipdb.com/check/"
  virustotal_ip_base: "https://www.virustotal.com/gui/ip-address/"
  virustotal_domain_base: "https://www.virustotal.com/gui/domain/"
  virustotal_hash_base: "https://www.virustotal.com/gui/file/"


rules_dir: rules
correlation_window_minutes: 15


output_formats:
  parquet: true
  json: true
